### ISSUE TITLE
All states are not updated

### ISSUE THREAD

**Issue by diouk44** [tiramiseb/calaos-ha#2]
Hello !

Since home assistant core update 2023.7.0, all states are not updated

```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.calaos.coordinator
Source: custom_components/calaos/coordinator.py:109
Integration: Calaos (documentation, issues)
First occurred: 18:48:45 (1 occurrences)
Last logged: 18:48:45

unknown error while polling: 'state'
```

**Comment by willoma** [comment]
Do you have more details? Are you able to reproduce this? I don't have this problem here...

If you can reproduce the problem, could you please add (or modify) the following lines in `configuration.yaml`, restart HA and check for lines related to calaos (especially to *pycalaos*) in `home-assistant.log`?

```yaml
logger:
  default: warning
  logs:
    custom_components.calaos.config_flow: debug
    custom_components.calaos.coordinator: debug
    custom_components.calaos.device_trigger: debug
    custom_components.calaos.entity: debug
    custom_components.calaos.light: debug
    custom_components.calaos.no_entity: debug
    custom_components.calaos.switch: debug
    pycalaos: debug
    pycalaos.item: debug
```
